# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prufer_sequence_generator_cpp <- function(N, n, k1, k2) {
    .Call(`_PruferConcept_prufer_sequence_generator_cpp`, N, n, k1, k2)
}

log_forest_count_cpp <- function(N, n, k1, k2, roots_known = TRUE) {
    .Call(`_PruferConcept_log_forest_count_cpp`, N, n, k1, k2, roots_known)
}

log_likelihood_cpp <- function(data, sequence, components, seq_type, cluster = FALSE) {
    .Call(`_PruferConcept_log_likelihood_cpp`, data, sequence, components, seq_type, cluster)
}

log_sampling_probability_cpp <- function(N, n, k1, k2, nb_mean, nb_size, components_mean) {
    .Call(`_PruferConcept_log_sampling_probability_cpp`, N, n, k1, k2, nb_mean, nb_size, components_mean)
}

classify_seq2_cpp <- function(seq2, N, n, k1, k2) {
    .Call(`_PruferConcept_classify_seq2_cpp`, seq2, N, n, k1, k2)
}

generate_samples_batch_cpp <- function(Nreps, n_sampled, nb_mean = 0, nb_size = 0, components_mean = 0, fix_N = 0L, fix_k = 0L) {
    .Call(`_PruferConcept_generate_samples_batch_cpp`, Nreps, n_sampled, nb_mean, nb_size, components_mean, fix_N, fix_k)
}

compute_posterior_batch_cpp <- function(data, samples_list, params) {
    .Call(`_PruferConcept_compute_posterior_batch_cpp`, data, samples_list, params)
}

