// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// prufer_sequence_generator_cpp
List prufer_sequence_generator_cpp(int N, int n, int k1, int k2);
RcppExport SEXP _PruferConcept_prufer_sequence_generator_cpp(SEXP NSEXP, SEXP nSEXP, SEXP k1SEXP, SEXP k2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< int >::type k2(k2SEXP);
    rcpp_result_gen = Rcpp::wrap(prufer_sequence_generator_cpp(N, n, k1, k2));
    return rcpp_result_gen;
END_RCPP
}
// log_forest_count_cpp
double log_forest_count_cpp(int N, int n, int k1, int k2, bool roots_known);
RcppExport SEXP _PruferConcept_log_forest_count_cpp(SEXP NSEXP, SEXP nSEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP roots_knownSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< int >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< bool >::type roots_known(roots_knownSEXP);
    rcpp_result_gen = Rcpp::wrap(log_forest_count_cpp(N, n, k1, k2, roots_known));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_cpp
double log_likelihood_cpp(IntegerVector data, List sequence, int components, std::string seq_type, bool cluster);
RcppExport SEXP _PruferConcept_log_likelihood_cpp(SEXP dataSEXP, SEXP sequenceSEXP, SEXP componentsSEXP, SEXP seq_typeSEXP, SEXP clusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< int >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< std::string >::type seq_type(seq_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type cluster(clusterSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_cpp(data, sequence, components, seq_type, cluster));
    return rcpp_result_gen;
END_RCPP
}
// log_sampling_probability_cpp
double log_sampling_probability_cpp(int N, int n, int k1, int k2, double nb_mean, double nb_size, double components_mean);
RcppExport SEXP _PruferConcept_log_sampling_probability_cpp(SEXP NSEXP, SEXP nSEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP nb_meanSEXP, SEXP nb_sizeSEXP, SEXP components_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< int >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< double >::type nb_mean(nb_meanSEXP);
    Rcpp::traits::input_parameter< double >::type nb_size(nb_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type components_mean(components_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(log_sampling_probability_cpp(N, n, k1, k2, nb_mean, nb_size, components_mean));
    return rcpp_result_gen;
END_RCPP
}
// classify_seq2_cpp
int classify_seq2_cpp(IntegerVector seq2, int N, int n, int k1, int k2);
RcppExport SEXP _PruferConcept_classify_seq2_cpp(SEXP seq2SEXP, SEXP NSEXP, SEXP nSEXP, SEXP k1SEXP, SEXP k2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< int >::type k2(k2SEXP);
    rcpp_result_gen = Rcpp::wrap(classify_seq2_cpp(seq2, N, n, k1, k2));
    return rcpp_result_gen;
END_RCPP
}
// generate_samples_batch_cpp
List generate_samples_batch_cpp(int Nreps, int n_sampled, double nb_mean, double nb_size, double components_mean, int fix_N, int fix_k);
RcppExport SEXP _PruferConcept_generate_samples_batch_cpp(SEXP NrepsSEXP, SEXP n_sampledSEXP, SEXP nb_meanSEXP, SEXP nb_sizeSEXP, SEXP components_meanSEXP, SEXP fix_NSEXP, SEXP fix_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Nreps(NrepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sampled(n_sampledSEXP);
    Rcpp::traits::input_parameter< double >::type nb_mean(nb_meanSEXP);
    Rcpp::traits::input_parameter< double >::type nb_size(nb_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type components_mean(components_meanSEXP);
    Rcpp::traits::input_parameter< int >::type fix_N(fix_NSEXP);
    Rcpp::traits::input_parameter< int >::type fix_k(fix_kSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_samples_batch_cpp(Nreps, n_sampled, nb_mean, nb_size, components_mean, fix_N, fix_k));
    return rcpp_result_gen;
END_RCPP
}
// compute_posterior_batch_cpp
List compute_posterior_batch_cpp(IntegerVector data, List samples_list, List params);
RcppExport SEXP _PruferConcept_compute_posterior_batch_cpp(SEXP dataSEXP, SEXP samples_listSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type samples_list(samples_listSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_posterior_batch_cpp(data, samples_list, params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PruferConcept_prufer_sequence_generator_cpp", (DL_FUNC) &_PruferConcept_prufer_sequence_generator_cpp, 4},
    {"_PruferConcept_log_forest_count_cpp", (DL_FUNC) &_PruferConcept_log_forest_count_cpp, 5},
    {"_PruferConcept_log_likelihood_cpp", (DL_FUNC) &_PruferConcept_log_likelihood_cpp, 5},
    {"_PruferConcept_log_sampling_probability_cpp", (DL_FUNC) &_PruferConcept_log_sampling_probability_cpp, 7},
    {"_PruferConcept_classify_seq2_cpp", (DL_FUNC) &_PruferConcept_classify_seq2_cpp, 5},
    {"_PruferConcept_generate_samples_batch_cpp", (DL_FUNC) &_PruferConcept_generate_samples_batch_cpp, 7},
    {"_PruferConcept_compute_posterior_batch_cpp", (DL_FUNC) &_PruferConcept_compute_posterior_batch_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PruferConcept(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
